# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set args and environment variable
ARG VITE_API_URI

ENV VITE_API_URI=${VITE_API_URI}

# Set the working directory in the container
WORKDIR /gracefulshutdown-frontend

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy only the necessary files, excluding the 'node_modules' directory
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]




