version: "3.7"

services:

  # CLIENT
  client:
    build:
      context: ./CLIENT # This specifies the directory for the dockerfile of the server service
      dockerfile: Dockerfile.prod
      args:
        - "VITE_API_URI=${VITE_API_URI}"
    image: ${USERNAME}/frontend
    labels:
      - ${USERNAME}/frontend:latest
    container_name: frontend
    restart: always
    networks:
      - nginx-web
    env_file:
      - .env.prod # ensure to point the path to the env file
    environment:
      - "VITE_API_URI=${VITE_API_URI}" # EX. "VAR_NAME=value"
    ports:
      - 5173:5173
    depends_on:
      - server

  # SERVER
  server:
    build:
      context: ./SERVER # This specifies the directory for the dockerfile of the server service
      dockerfile: Dockerfile
      args:
        - "PORT=${PORT}"
        - "MONGODB_URI=${MONGODB_URI}"
    image: ${USERNAME}/backend
    labels:
      - ${USERNAME}/backend:latest
    container_name: backend
    restart: always
    networks:
      - nginx-web
    env_file:
      - .env.prod # ensure to point the path to the env file
    ports:
    - "${PORT}:${PORT}"
    environment:
      - "PORT=${PORT}"
      - "MONGODB_URI=${MONGODB_URI}" # EX. "VAR_NAME=value"
    volumes:
      - backend-data:/gracefulshutdown/logs  # Mount a volume for persisting data on the server 

  # PROXY_MANAGER
  proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy
    restart: unless-stopped
    networks:
      - nginx-web
    env_file:
      - .env.prod # ensure to point the path to the env file
    ports:
      - '${WEBPORT}:80'  # container will be exposed to the outside on this port
      - '81:81'
    depends_on:
      - client
      - server
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./CONFIG/nginx.conf:/data/nginx/custom/http_top.conf

networks:
  nginx-web:
    driver: bridge

volumes:
  backend-data: {}


