version: "3.7"

services:

  # SERVER
  server:
    build:
      context: ./SERVER # This specifies the directory for the dockerfile of the server service
      dockerfile: Dockerfile
    image: hardarmyyy/nginx-gracefulshutdown-server-05-09
    labels:
      hardarmyyy/nginx-gracefulshutdown-server-05-09: latest
    container_name: nginx-backend-server
    restart: always
    networks:
      - gracefulshutdown-network
    env_file:
      - .env # ensure to point the path to the env file
    environment:
      - "PORT=${PORT}"
      - "MONGODB_URI=${MONGODB_URI}" # EX. "VAR_NAME=value"
    depends_on:
      - db
    volumes:
      - gracefulshutdown-data:/gracefulshutdown/logs  # Mount a volume for persisting data on the server 


  # MongoDB database
  db:
    image: mongo:4.4
    labels: 
      hardarmyyy/nginx-gracefulshutdown-mongodb-05-09: latest
    container_name: nginx-backend-mongodb
    restart: always
    networks:
      - gracefulshutdown-network
    volumes:
      - mongo-data:/data/db  # # Mount a volume for persisting data on the db

  # Web service
  web:
    build:
      context: ./WEB-SERVICE # This specifies the directory for the dockerfile of the web service
      dockerfile: Dockerfile
    image: hardarmyyy/nginx-gracefulshutdown-web-05-09
    labels:
      hardarmyyy/nginx-gracefulshutdown-web-05-09: latest
    container_name: nginx-backend-web
    restart: always
    networks:
      - gracefulshutdown-network
    env_file:
      - .env # ensure to point the path to the env file
    ports: 
      - "${WEBPORT}:80"  # container will be exposed to the outside on this port
    depends_on:
      - server

networks:
  gracefulshutdown-network:
    driver: bridge

volumes:
  mongo-data: {}
  gracefulshutdown-data: {}

