version: "3.7"

services:

  # CLIENT
  client:
    build:
      context: ./CLIENT # This specifies the directory for the dockerfile of the server service
      dockerfile: Dockerfile
    image: ${USERNAME}/nginx-web-frontend-app
    labels:
      ${USERNAME}/nginx-web-frontend-app: latest
    container_name: frontend
    network_mode: "host"
    env_file:
      - .env # ensure to point the path to the env file
    environment:
      - "VITE_API_URI=${VITE_API_URI}" # EX. "VAR_NAME=value"
    depends_on:
      - server

  # SERVER
  server:
    build:
      context: ./SERVER # This specifies the directory for the dockerfile of the server service
      dockerfile: Dockerfile
    image: ${USERNAME}/nginx-web-backend-app
    labels:
      ${USERNAME}/nginx-web-backend-app: latest
    container_name: backend
    restart: always
    networks:
      - gracefulshutdown-network
    env_file:
      - .env # ensure to point the path to the env file
    ports: 
    - "${PORT}:${PORT}" 
    environment:
      - "PORT=${PORT}"
      - "MONGODB_URI=${MONGODB_URI}" # EX. "VAR_NAME=value"
    depends_on:
      - db
    volumes:
      - server-data:/gracefulshutdown/logs  # Mount a volume for persisting data on the server 

  # MongoDB database
  db:
    image: mongo:4.4
    container_name: nginx-backend-mongodb
    restart: always
    networks:
      - gracefulshutdown-network
    volumes:
      - mongo-data:/data/db  # # Mount a volume for persisting data on the db

networks:
  gracefulshutdown-network:
    driver: bridge

volumes:
  server-data: {}
  mongo-data: {}

